version: '3.7'

services:
  demo-dev-api:
    image: demo-dev-api
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        PORT: 80
        PROFILE: dev
    container_name: demo-dev-api
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1G"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://172.17.0.1:8099/api/demo/v1/health-check" ]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 10s
    ports:
      - "8099:8080"
    volumes:
      - "/opt/logs/:/opt/logs"
      - "/opt/app/demo-api/:/opt/app/demo-api/"
